[package]
name = "pca"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "=1.0.44"
tera = "1.2.0"
rusty-machine = {path = "../../../nodejs/deps/rusty_machine"}
