[package]
name = "match_regex"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[lib]
name = "match_regex_lib"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
regex = "1.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "=0.2.61"
